### PR TITLE
support Pydantic V2

### LINKED ISSUE #48: support Pydantic v2
Currently Pydantic version is pinned to v1.
https://github.com/SupImDos/pydantic-argparse/blob/c07199879040f9cfd26f13b2cfbeb8105a3c830f/pyproject.toml#L23

Is is possible to loose this restriction to support Pydantic v2?

### PR DESCRIPTION
**Pull request by lucidfrontier45**
closes #48 

This PR adds lazy way of Pydantic V2 support by using `pydantic.v1` namespace.
Additionally absolute imports in the source files under `pyadntic_argparse` are replaced to relative imports.

### CODE REVIEW

**Comment by neumann-nico** [comment]
@SupImDos Any chance to get it merged/released?

**Comment by advait** [comment]
If you'd like to use this feature branch before it's merged (and you use poetry), try this in your pyproject.toml:
```toml
[tool.poetry.dependencies]
pydantic-argparse = { git = "https://github.com/lucidfrontier45/pydantic-argparse.git", branch = "feature/pydantic-v2" }
```

Thanks @lucidfrontier45 for the contrib!

**Comment by anastasds** [comment]
I reached out to @SupImDos about taking over this repository and have not received a response. I hear that the name transfer process can take a long time, so I've forked and renamed to `pydantic-args`; version `0.9.1` is available with Pydantic 2 support.

https://github.com/anastasds/pydantic-args
https://pypi.org/project/pydantic-args/

**Comment by anastasds** [comment]
(found a better name and edited my above comment accordingly commenting for notifications)

**Comment by nsheff** [comment]
Is anyone interested in updating this to *not* rely on the `pydantic.v1` interface in `pydantic` v2? because presumably at some point that could go away...

**Comment by wabiloo** [comment]
@anastasds is there any reason your version in pydantic2-argparse is locked to pydantic v2.5.3?

**Comment by SupImDos** [comment]
Thanks @lucidfrontier45 for the contribution. Closing this PR in favour of https://github.com/SupImDos/pydantic-argparse/pull/55. I will address these changes and the roadmap forward in https://github.com/SupImDos/pydantic-argparse/issues/48.

**Pull request closed without merging**
