### PR TITLE
Make project compatible with Python 3.7+

### LINKED ISSUE #35: Consider supporting older Python versions?
Hello! Firstly, thank you for this package. I really like it and I want to use it in a project I'm developing.

The project I work on has the minimal Python version of 3.7 (currently the lowest supported version), but your package uses the version 3.9. Hence, my question: **would you consider “downgrading” your project to also support Python 3.7 and 3.8?** I understand, that you may not want to do this, and it's fine! I could do all the work myself. If you do not want to maintain older Python version at all, it's fine too: I would then fork it and do it on my end. Thanks!

### PR DESCRIPTION
**Pull request by kytta**
Closes #35

### CODE REVIEW

**Comment by kytta** [comment]
So far, it's a lot of find-and-replace work. I have replaced the types, but `get_origin()` needs to be replaced, too. As of now, it's 447 tests failed, 12 tests passed :)

**Comment by kytta** [comment]
Alright, I have resolved almost everything that needed to be resolved. There is one last problem, though.

The test `argparse.test_parser.py::test_invalid_arguments` fails when a subparser doesn't have a `dest`. It happens right on the last step, where the error message gets generated. This was a known bug (see https://github.com/python/cpython/issues/73484) which was fixed in 3.11 (https://github.com/python/cpython/pull/3680) and backported to 3.9 (https://github.com/python/cpython/pull/27304). Since it's a module function, we can't reliably backport/patch it.

@SupImDos any ideas what we can do here? I propose adding a default `metavar` to the `SubParsersAction` with the value of, e.g., `"COMMAND"`:

```diff
class SubParsersAction(argparse._SubParsersAction):
+    def __init__(self, *args, **kwargs):
+        kwargs.setdefault("metavar", "COMMAND")
+        super().__init__(*args, **kwargs)
```

Basically, this would be analogue to this:

```py
parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(metavar="COMMAND", required=True)
test_sub = subparsers.add_parser("test")
test_sub.add_argument("--flag", type=bool, default=False)
```

```sh
$ python3.7 parsing.py --help
usage: parsing.py [-h] COMMAND ...

positional arguments:
  COMMAND

optional arguments:
  -h, --help  show this help message and exit

$ python3.7 parsing.py       
usage: parsing.py [-h] COMMAND ...
parsing.py: error: the following arguments are required: COMMAND
```

<details>
<summary>The same code under Python 3.7, but without metavar</summary>

```sh
$ python3.7 parsing.py --help
usage: parsing.py [-h] {test} ...

positional arguments:
  {test}

optional arguments:
  -h, --help  show this help message and exit

$ python3.7 parsing.py       
Traceback (most recent call last):
  File "parsing.py", line 9, in <module>
    parser.parse_args()
  File "/Users/nikita/.pyenv/versions/3.7.16/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/nikita/.pyenv/versions/3.7.16/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/nikita/.pyenv/versions/3.7.16/lib/python3.7/argparse.py", line 2022, in _parse_known_args
    ', '.join(required_actions))
TypeError: sequence item 0: expected str instance, NoneType found
```

</details>

**Comment by SupImDos** [comment]
@kytta 
Wow, thanks so much for all your hard work. This looks great!

### 1. Minor Type Checking Error
Looks like we might need to add a `type: ignore[union-attr]` to the `BooleanOptionalAction` backport so the CI/CD passes. The Python standard library typing is always a bit dodgy.

https://github.com/kytta/pydantic-argparse/blob/python-37/pydantic_argparse/argparse/actions.py#L194
```diff
-            setattr(namespace, self.dest, not option_string.startswith('--no-'))
+            setattr(namespace, self.dest, not option_string.startswith('--no-'))  # type: ignore[union-attr]
```

### 2. Argparse SubParser Backport Bug
Hmm this is an interesting one. Ideally I would like to keep the same behaviour (i.e., show the different command options across the different versions. i.e.,
```shell
$ python examples/commands.py
usage: Example Program [-h] [-v] [--verbose] {build,serve} ...
Example Program: error: the following arguments are required: {build,serve}
```

I can think of a few things we can do:

1. **Default Static Metavar**
   As you suggest above, we can provide a default/dummy `metavar` to the `SubParsersAction`.

   `pydantic_argparse/argparse/actions.py`
   ```diff
   class SubParsersAction(argparse._SubParsersAction):
   +    def __init__(self, *args, **kwargs):
   +        kwargs.setdefault("metavar", "COMMAND")
   +        super().__init__(*args, **kwargs)
   ```

   However, this means the help does not display the actual _options_ we have (i.e., in this case `{build,serve}` - just the `COMMAND` string.

   ```shell
   $ python examples/commands.py
   usage: Example Program [-h] [-v] [--verbose] COMMAND ...
   Example Program: error: the following arguments are required: COMMAND
   ```

2. **Dynamic Metavar Using Property**
   Another option we have is to hijack the `metavar` value using a `@property`. This way we can dynamically construct the string with `self.choices` to provide the desired `{build,serve}` string. It is a bit messy though, and we have to provide a dummy `@metavar.setter` method. Not sure if I really like this option.

   `pydantic_argparse/argparse/actions.py`
   ```diff
   class SubParsersAction(argparse._SubParsersAction):
   +   @property
   +   def metavar(self) -> Optional[str]:
   +       """Docstring...
   +
   +       Returns:
   +           Optional[str]: ...
   +       """
   +       # Explanation?
   +       # Type checking?
   +       # What if no `self.choices`?
   +       return '{' + ','.join(self.choices) + '}'
   +
   +   @metavar.setter
   +   def metavar(self, value: Any) -> None:
   +       """Docstring...
   +
   +       Args:
   +           value (Any): ...
   +       """
   +       # Dummy method, we can't allow it to be set
   +       return None
   ```

   The desired result is produced below.

   ```shell
   $ python examples/commands.py
   usage: Example Program [-h] [-v] [--verbose] {build,serve} ...
   Example Program: error: the following arguments are required: {build,serve}
   ```

3. **Backport and MonkeyPatch `_get_action_name`**
   Finally, we could provide our own monkey-patch for the fixed `_get_action_name` method as below. This would provide the desired functionality and be relatively clean? I think I like this, but I'm not sure if we might introduce some issues by monkey-patching the standard library.

   `pydantic_argparse/argparse/patches.py`
   ```python
   """Docstring..."""


   # Standard
   import argparse
   import sys

   # Typing
   from typing import Optional


   # Some comments here explaining why we do this
   # https://github.com/python/cpython/blob/main/Lib/argparse.py#L739-L751
   if sys.version_info < (3, 9):
       def _get_action_name(argument: Optional[argparse.Action]) -> Optional[str]:
           """Docstring."""
           if argument is None:
               return None
           elif argument.option_strings:
               return '/'.join(argument.option_strings)
           elif argument.metavar not in (None, argparse.SUPPRESS):
               return argument.metavar  # type: ignore[return-value]
           elif argument.dest not in (None, argparse.SUPPRESS):
               return argument.dest
           elif argument.choices:
               return '{' + ','.join(argument.choices) + '}'
           else:
               return None

       # Monkey-Patch
       argparse._get_action_name = _get_action_name
   ```

   The desired result is produced below.

   ```shell
   $ python examples/commands.py
   usage: Example Program [-h] [-v] [--verbose] {build,serve} ...
   Example Program: error: the following arguments are required: {build,serve}
   ```

@kytta I think at the moment I prefer **(3)**. What do you think?

**Comment by kytta** [comment]
> Looks like we might need to add a `type: ignore[union-attr]` to the `BooleanOptionalAction` backport so the CI/CD passes.

Yup, done!

---

> ### 2. Argparse SubParser Backport Bug
> 
> Hmm this is an interesting one. Ideally I would like to keep the same behaviour (i.e., show the different command options across the different versions.
>
> [...]
> 
> I can think of a few things we can do:
> 
>     1. **Default Static Metavar**

This would be my favourite way to do this, but I understand that having every command as a metavar is more helpful than just `"COMMAND"`.

>     2. **Dynamic Metavar Using Property**

Too messy, such that the code becomes less readable.

>     3. **Backport and MonkeyPatch `_get_action_name`**

I am usually not a fan of monkey patching module functions, but this is pretty clean, and we can turn it off on newer Python versions with `sys.version_info` check.

> @kytta I think at the moment I prefer **(3)**. What do you think?

Yeah, let's do that.

**Comment by kytta** [comment]
@SupImDos another thing I wanted to ask: How do you like `typing_extensions` and `importlib_metadata` to be imported? They currently use two different approaches, and I want to use the same one for both of them:

1. **Version-checked.** We would only install the backports on those Python versions, where they're needed, and check the version at runtime:
   
   ```py
   # foobar.py
   if sys.version < (3, 8):
       import importlib_metadata as metadata
   else:
       from importlib import metadata
   ```
   
   ```toml
   # pyproject.toml
   
   [tool.poetry.dependencies]
   # [...]
   importlib_metadata = { version = ">=4", python = "<3.8" }
   ```

2. **Always import**. We don't care about the Python version and always use the backport:
   
   ```py
   # foobar.py
   import importlib_metadata as metadata
   ```
   
   ```toml
   # pyproject.toml
   
   [tool.poetry.dependencies]
   importlib_metadata = ">=4"
   ```

I like the **(1)** better, as it allows us to ship less dependencies to the most users (as I don't think that many people use Python 3.7 in production, especially for command-line-apps). It is also very easy to remove later with [pyupgrade](https://github.com/asottile/pyupgrade). But the code is cleaner with the second option 🤔

**Comment by SupImDos** [comment]
> How do you like `typing_extensions` and `importlib_metadata` to be imported?
> 1. **Version-checked**. We would only install the backports on those Python versions, where they're needed, and check the version at runtime...

This feels like the correct way to do it. As you say, it allows us to ship less dependencies to the most users.

> 2. **Always import**. We don't care about the Python version and always use the backport...

Less code branching is a lot cleaner and it is tempting. But I think (1) is still better in a practical sense.

@kytta I agree with you that we should go with **(1)**  😃 

I am interested to see how the code coverage is calculated with branches that only execute in certain Python versions. We will have to see 🤔

**Comment by kytta** [comment]
> I am interested to see how the code coverage is calculated with branches that only execute in certain Python versions. We will have to see 🤔

This is also an interesting moment.

A while ago I have noticed the comment `# pragma: <3.8, cover` somewhere, and it was supposed to disable coverage on the branches on specific Python repos. I have used it in my project, and it worked.

Now, I have tried to also use it here (see commit c2bcc6ce305cea9629dc281b52a7a34bf2c34c5a), but it didn't work (at least locally). For me, `poe test` reports missing lines, these version checks to be exact.

I then tried to look this pragma up, but neither coverage nor pytest-cov docs mention anything other than `pragma: no cover`…

If we can't get this to work, I propose setting `pragma: no cover` on lines for Python 3.7–3.8 and only run coverage on the newer versions

**Comment by SupImDos** [comment]
@kytta 
I've done a bit of a look into the `# pragma: >x.y cover` and I think I might have worked it out. As far as I can tell it looks like it comes from the [`covdefaults`](https://pypi.org/project/covdefaults/) package.

I had a look at your `venvy` project which uses [`# pragma: <3.8 cover`](https://github.com/kytta/venvy/blob/main/venvy/main.py#L12) and [`# pragma: >=3.8 cover`](https://github.com/kytta/venvy/blob/main/venvy/main.py#L14), and it looks like it has `covdefaults` [installed](https://github.com/kytta/venvy/blob/main/pyproject.toml#L55).

I think this works? `covdefaults` looks pretty useful. Maybe we should do:
1. `poetry add --group dev covdefaults`
2. Modify `pyproject.toml`
   ```diff
   [tool.coverage.run]
   - branch = true
   + plugins = ["covdefaults"]
   -
   - [tool.coverage.report]
   - show_missing = true
   - exclude_lines = [
   -   "if __name__ == .__main__.:",
   - ]
   ```

Does this sound right? What do you think?

**Comment by kytta** [comment]
> @kytta I've done a bit of a look into the `# pragma: >x.y cover` and I think I might have worked it out. As far as I can tell it looks like it comes from the [`covdefaults`](https://pypi.org/project/covdefaults/) package.
> 
> I had a look at your `venvy` project which uses [`# pragma: <3.8 cover`](https://github.com/kytta/venvy/blob/main/venvy/main.py?rgh-link-date=2023-01-09T11%3A26%3A00Z#L12) and [`# pragma: >=3.8 cover`](https://github.com/kytta/venvy/blob/main/venvy/main.py?rgh-link-date=2023-01-09T11%3A26%3A00Z#L14), and it looks like it has `covdefaults` [installed](https://github.com/kytta/venvy/blob/main/pyproject.toml?rgh-link-date=2023-01-09T11%3A26%3A00Z#L55).
> 
> I think this works? `covdefaults` looks pretty useful. Maybe we should do:
> 
>     1. `poetry add --group dev covdefaults`
> 
>     2. Modify `pyproject.toml`
>        ```diff
>        [tool.coverage.run]
>        - branch = true
>        + plugins = ["covdefaults"]
>        -
>        - [tool.coverage.report]
>        - show_missing = true
>        - exclude_lines = [
>        -   "if __name__ == .__main__.:",
>        - ]
>        ```
> 
> 
> Does this sound right? What do you think?

Oh right, I completely forgot about this package! Yeah, this looks good, I'll add this to pyproject.toml

**Comment by kytta** [comment]
Alright, everything is fixed, and the only thing left is the coverage for some of the backports:

pydantic_argparse/argparse/actions.py:160
pydantic_argparse/argparse/actions.py:193
pydantic_argparse/argparse/patches.py:39

Should we even cover those? I mean, it's not even our code... 🤔

**Comment by SupImDos** [comment]
@kytta 
Thanks so much, this looks great!

> Alright, everything is fixed, and the only thing left is the coverage for some of the backports
> Should we even cover those? I mean, it's not even our code... :thinking:

You're right, I would be happy with a `# pragma: no cover` for now, as you say its not our code anyway. I think the CI/CD is only failing because of the <100% coverage (which will be fixed by the pragmas) and a whitespace issue in `patches.py`.

I'll do my best to review this properly as soon as I can 😃

**Comment by kytta** [comment]
Alright, should be done now! All checks run fine on my machine 👌🏻

**Review by SupImDos — APPROVED** [review]
Looks great, thanks again for all this work!

**Pull request merged**
